-- 1. Create the products table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null,
  stock integer not null default 0,
  image_url text, -- To store the Supabase Storage URL
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable RLS (Row Level Security)
alter table public.products enable row level security;

-- 3. Policy: Public Read Access (Everyone can see products)
create policy "Public products are viewable by everyone."
  on public.products for select
  using ( true );

-- 4. Policy: Admin Insert Access (Only logged-in users can create)
create policy "Users can insert products."
  on public.products for insert
  with check ( auth.role() = 'authenticated' );

-- 5. Policy: Admin Update Access (Only logged-in users can update)
create policy "Users can update products."
  on public.products for update
  using ( auth.role() = 'authenticated' );

-- 6. Policy: Admin Delete Access (Only logged-in users can delete)
create policy "Users can delete products."
  on public.products for delete
  using ( auth.role() = 'authenticated' );
