-- Create the products table if it doesn't exist
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null,
  stock integer not null default 0,
  image_url text, -- Can be null for 'Coming Soon' logic
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Basic Policies (RLS) to ensure data is secure
-- Enable Row Level Security
alter table public.products enable row level security;

-- Policy: Anyone can view products (Public Store)
create policy "Public products are viewable by everyone."
  on public.products for select
  using ( true );

-- Policy: Only authenticated users can insert/update/delete (Admin)
-- Note: You should ideally have a specific role or check for email, 
-- but for this MVP, any logged-in user (authenticated) is an admin.
create policy "Users can insert their own products."
  on public.products for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can update their own products."
  on public.products for update
  using ( auth.role() = 'authenticated' );

create policy "Users can delete their own products."
  on public.products for delete
  using ( auth.role() = 'authenticated' );

-- Storage Bucket Setup (If you want to use Storage)
-- Run this in the Storage section or SQL Editor if supported
insert into storage.buckets (id, name, public)
values ('products_image', 'products_image', true);

-- Storage Policies
create policy "Give public access to product images"
  on storage.objects for select
  using ( bucket_id = 'products_image' );

create policy "Enable authenticated uploads"
  on storage.objects for insert
  with check ( bucket_id = 'products_image' and auth.role() = 'authenticated' );
