// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzlBKSJPLwspacE3T1wxHGI4Jt5QsMHWI',
    appId: '1:907263499276:web:67ce2707fdffba2232e229',
    messagingSenderId: '907263499276',
    projectId: 'creaciones-baby',
    authDomain: 'creaciones-baby.firebaseapp.com',
    storageBucket: 'creaciones-baby.firebasestorage.app',
    measurementId: 'G-8T4L9JWM1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpTQkteEzHO0EcO6uXtMQQIo0YQQVqJuA',
    appId: '1:907263499276:android:ea9c34485b65249232e229',
    messagingSenderId: '907263499276',
    projectId: 'creaciones-baby',
    storageBucket: 'creaciones-baby.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM98JJF1ULWpKYbnfgEkvZ2PfyDJ4MpWU',
    appId: '1:907263499276:ios:f3a681e249d8de1432e229',
    messagingSenderId: '907263499276',
    projectId: 'creaciones-baby',
    storageBucket: 'creaciones-baby.firebasestorage.app',
    iosBundleId: 'com.creacionesbaby.creacionesbaby',
  );

}